### PR TITLE
Update behat.yml to work with Chrome driver 75

### PR DESCRIPTION
**Pull request by aczietlow**
Update chrome driver configuration to resolve issue #7

### CODE REVIEW

**Comment by lmakarov** [comment]
@aczietlow is this still work in progress (per https://github.com/docksal/behat/issues/7#issuecomment-537086591)?

**Comment by stevenlafl** [comment]
Why disable-gpu and headless options? Does this help in some significant way? The main thing that is needed is the w3c part. If those help solve other issues, I'd like to know what @aczietlow

**Comment by aczietlow** [comment]
@stevenlafl I don't have a wonderful answer, I was pulling things from deep within the rabbit hole of this problem. I'm more than happy to remove them, if it results actually fixing the issue. 

Maybe have been from this thread. https://github.com/minkphp/MinkSelenium2Driver/issues/293#issuecomment-519920991

**Comment by paulsheldrake** [comment]
This is what worked for me

```docksal.yml
  # Browser
  browser:
    hostname: browser
    image: selenium/standalone-chrome:3.141.59-oxygen
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```

```behat.yml
  extensions:
    Behat\MinkExtension:
      # URL of the site when accessed locally.
      base_url: http://web
      # For real browser testing and tests requiring JS use selenium2 driver.
      # Tag features/scenarious with @javascript to use the selenium2 driver.
      javascript_session: selenium2
      # Configure browser to be used. Browser must be available on wd_host.
      # Stick with chrome by default. It's 2x faster than firefox or phantomjs (your results may vary).
      browser_name: chrome
      files_path: ./features/files
      selenium2:
        wd_host: http://browser:4444/wd/hub
        capabilities: { 
          "browser": "chrome",
          "version": "*", 
          "extra_capabilities": { 
            "chromeOptions": { 
              "w3c": false 
             } 
           } 
         }
```

**Comment by lmakarov** [comment]
Closing as outdated.

**Pull request closed without merging**
